################################################################################
# CONFIGURATION FILE FOR DRICH EICrecon USAGE
# - use with EICrecon `git` branch `main`
################################################################################

### EICrecon plugins
plugins:
  - janadot
  # - dump_flags

### PODIO collections to include in the output
podio:
  output_include_collections:
    ### simulation
    - DRICHHits
    - MCParticles
    ### digitization
    - DRICHRawHits
    - DRICHRawHitsAssociations

### EICrecon log levels
log_levels:
  eicrecon: info
  DRICH:
    DRICHRawHits: info

### common settings
jana:
  nevents: 0
  debug_plugin_loading: 1
acts:
  MaterialMap: calibrations/materials-map.cbor
