###############################################################################
# DRICH Configuration Parameters Sandbox
# - eventually we will have a proper config file in EICrecon itself,
#   but already here we can demonstrate that capability, as shown below
# - once we have such config files in EICrecon, we will likely not need to have
#   this `recon.rb` wrapper and our own `yaml` files
# - any settings below will override the current default settings, which are
#   stored in `EICrecon/src/detectors/DRICH/DRICH.cc`
# - the ability to parse units in EICrecon may not yet be merged to `main`
###############################################################################

DRICH:
  ### digitizer
  DRICHRawHits:
    seed: 5
    hitTimeWindow: 20.0*ns
    pixelSize: 3.0*mm
  ### track projection
  DRICHTracks:
    Aerogel:
      numPlanes: 5
    Gas:
      numPlanes: 10
  ### IRT PID
  DRICHIrtCherenkovParticleID:
    numRIndexBins: 100
    Aerogel:
      zbins: 5
      referenceRIndex: 1.0190
    Gas:
      zbins: 10
      referenceRIndex: 1.00076
  ### example array setting
  ExampleArray:
    - 1
    - 2
    - 3
    - 4
    - 5


################################################################################
# Common configuration parameters (collections, plugins, log levels, etc.)
################################################################################

### EICrecon plugins
plugins:
  - benchmarks_pid
  - janadot
  # - dump_flags

### PODIO collections to include in the output
podio:
  output_include_collections:
    ### simulation
    - DRICHHits
    - MCParticles
    ### digitization
    - DRICHRawHits
    - DRICHRawHitsAssociations
    ### track projections
    - DRICHAerogelTracks
    - DRICHGasTracks
    ### IRT PID
    - DRICHAerogelIrtCherenkovParticleID
    - DRICHGasIrtCherenkovParticleID
    - DRICHMergedIrtCherenkovParticleID
    ### Reconstructed Particles
    - ReconstructedChargedParticles
    - ReconstructedChargedParticleAssociations
    - ReconstructedChargedParticlesWithDRICHPID
    - ReconstructedChargedParticleAssociationsWithDRICHPID

### EICrecon log levels
log_levels:
  eicrecon: info
  richgeo: info
  benchmarks_pid: info
  DRICH:
    DRICHRawHits: info
    DRICHTracks: info
    DRICHIrtCherenkovParticleID: info
    DRICHMergedIrtCherenkovParticleID: info

### common settings
jana:
  nevents: 0
  debug_plugin_loading: 1
acts:
  MaterialMap: calibrations/materials-map.cbor
