################################################################################
# CONFIGURATION FILE FOR DRICH EICrecon USAGE
# - use with EICrecon `git` branch `irt-algo` or `irt-algo-stable`
################################################################################

### EICrecon plugins
plugins:
  - benchmarks_pid
  - janadot
  # - dump_flags

### PODIO collections to include in the output
podio:
  output_include_collections:
    ### simulation
    - DRICHHits
    ### digitization
    - DRICHRawHits
    - DRICHRawHitsAssociations
    ### track projections
    - DRICHAerogelTracks
    - DRICHGasTracks
    ### IRT PID
    - DRICHAerogelIrtCherenkovParticleID
    - DRICHGasIrtCherenkovParticleID
    - DRICHMergedCherenkovParticleID
    ### Reconstructed Particles
    - ReconstructedChargedParticles
    - ReconstructedChargedParticleAssociations
    - ReconstructedChargedParticlesWithDRICHPID
    - ReconstructedChargedParticleAssociationsWithDRICHPID

### EICrecon log levels
log_levels:
  eicrecon: info
  richgeo: info
  benchmarks_pid: info
  DRICH:
    DRICHRawHits: info
    DRICHTracks: info
    DRICHIrtCherenkovParticleID: info
    DRICHMergedCherenkovParticleID: info

### common settings
jana:
  nevents: 0
  debug_plugin_loading: 1
acts:
  MaterialMap: calibrations/materials-map.cbor
