################################################################################
# CONFIGURATION FILE FOR DRICH EICrecon USAGE
# - use with EICrecon `git` branch `irt-algo` or `irt-algo-stable`
################################################################################

### EICrecon plugins
plugins:
  - janadot
  # - dump_flags

### PODIO collections to include in the output
podio:
  output_include_collections:
    ### simulation
    - DRICHHits
    - MCParticles
    ### digitization
    - DRICHRawHits
    - DRICHRawHitsAssociations
    ### track projections
    - DRICHAerogelTracks
    - DRICHGasTracks
    - DRICHMergedTracks
    ### IRT PID
    - DRICHAerogelIrtCherenkovParticleID
    - DRICHGasIrtCherenkovParticleID
    - DRICHMergedIrtCherenkovParticleID
    ### Reconstructed Particles
    - ReconstructedChargedParticles
    - ReconstructedChargedParticleAssociations
    - ReconstructedChargedParticlesWithDRICHPID
    - ReconstructedChargedParticleAssociationsWithDRICHPID

### EICrecon log levels
log_levels:
  eicrecon: info
  richgeo: info
  DRICH:
    DRICHRawHits: debug
    DRICHTracks: info
    DRICHMergedTracks: info
    DRICHIrtCherenkovParticleID: info
    DRICHMergedIrtCherenkovParticleID: info

### common settings
jana:
  nevents: 0
  debug_plugin_loading: 1
acts:
  MaterialMap: calibrations/materials-map.cbor

### DRICH Configuration Overrides
DRICH:
  DRICHRawHits:
    enableNoise: true
