################################################################################
# CONFIGURATION FILE FOR DRICH EICrecon USAGE
################################################################################

### EICrecon plugins
plugins:
  - janadot
  # - dump_flags

### PODIO collections to include in the output
podio:
  output_collections:
    ### simulation
    - DRICHHits
    - MCParticles
    ### digitization
    - DRICHRawHits
    - DRICHRawHitsAssociations
    ### track projections
    - DRICHAerogelTracks
    - DRICHGasTracks
    - DRICHMergedTracks
    ### IRT PID
    - DRICHAerogelIrtCherenkovParticleID
    - DRICHGasIrtCherenkovParticleID
    - DRICHMergedIrtCherenkovParticleID
    ### Reconstructed Particles
    - ReconstructedChargedParticles
    - ReconstructedChargedParticleAssociations
    - ReconstructedChargedParticleIDs

### EICrecon log levels
log_levels:
  eicrecon: info
  richgeo: info
  DRICH:
    DRICHRawHits: info
    DRICHTracks: info
    DRICHMergedTracks: info
    DRICHIrtCherenkovParticleID: info
    DRICHMergedIrtCherenkovParticleID: info
  pid:
    ChargedParticlesWithAssociations: info

### common settings
jana:
  nevents: 0
  debug_plugin_loading: 1
acts:
  MaterialMap: calibrations/materials-map.cbor

### DRICH Configuration Overrides
DRICH:
  DRICHIrtCherenkovParticleID:
    cheatPhotonVertex: true
