###############################################################################
# DRICH Configuration Parameters Sandbox
# - demonstration of configuration parameter overrides for the dRICH
# - the ability to parse units in EICrecon may not yet be merged to `main`
###############################################################################

### DRICH Configuration #####################
DRICH:
  ### digitizer
  DRICHRawHits:
    seed: 5
    hitTimeWindow: 20.0*ns
    pixelSize: 3.0*mm
  ### track projection
  DRICHTracks:
    Aerogel:
      numPlanes: 5
    Gas:
      numPlanes: 10
  ### IRT PID
  DRICHIrtCherenkovParticleID:
    numRIndexBins: 100
    Aerogel:
      zbins: 5
      referenceRIndex: 1.0190
    Gas:
      zbins: 10
      referenceRIndex: 1.00076
  ### example array setting
  ExampleArray:
    - 1
    - 2
    - 3
    - 4
    - 5

### Output Collections ######################
podio:
  output_include_collections:
    - DRICHAerogelIrtCherenkovParticleID
    - DRICHGasIrtCherenkovParticleID
    - ReconstructedChargedParticles
    - ReconstructedChargedParticleAssociations
    - ReconstructedChargedParticleIDs
