# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2023 Christopher Dilks

name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  num_events: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

# BUILD ---------------------------------------------------------------------------
  build_data_model:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - { repo: EDM4eic, branch: main }
    steps:
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v3
      - uses: eic/run-cvmfs-osg-eic-shell@main
        with:
          platform-release: "jug_xl:nightly"
          setup: environ.sh
          run: |
            echo "[CI] CLONE REPOSITORIES"
            git clone https://github.com/eic/${{matrix.repo}}.git --branch ${{matrix.branch}}
            echo "[CI] BRANCHES"
            check_branches.sh
            echo "[CI] BUILD REPOSITORIES"
            build.sh ${{matrix.repo}}
      - uses: actions/upload-artifact@v3
        with:
          name: build_${{matrix.repo}}
          retention-days: 1
          path: |
            prefix

  build_github_modules:
    needs:
      - build_data_model
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - { repo: epic,     branch: main     }
          - { repo: irt,      branch: main     }
          - { repo: EICrecon, branch: irt-algo }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build_EDM4eic
      - uses: cvmfs-contrib/github-action-cvmfs@v3
      - uses: eic/run-cvmfs-osg-eic-shell@main
        with:
          platform-release: "jug_xl:nightly"
          setup: environ.sh
          run: |
            echo "[CI] CLONE REPOSITORIES"
            git clone https://github.com/eic/${{matrix.repo}}.git --branch ${{matrix.branch}}
            echo "[CI] BRANCHES"
            check_branches.sh
            echo "[CI] BUILD REPOSITORIES"
            build.sh ${{matrix.repo}}
      - uses: actions/upload-artifact@v3
        with:
          name: build_${{matrix.repo}}
          retention-days: 1
          path: |
            prefix

#TODO
#- build eicweb modules
#- build local drich-dev

# SIMULATION ----------------------------------------------------------------------

  # run_simulation:
  #   needs:
  #     - build_modules
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       test_num: [1, 4]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #     - uses: cvmfs-contrib/github-action-cvmfs@v3
  #     - uses: eic/run-cvmfs-osg-eic-shell@main
  #       with:
  #         platform-release: "jug_xl:nightly"
  #         setup: environ.sh
  #         run: |
  #           echo "[CI] JOB MATRIX:"
  #           echo "test_num = ${{matrix.test_num}}"
  #           echo "[CI] RUN SIMULATION:"
  #           simulate.py -t ${{matrix.test_num}} -n ${{env.num_events}} -o out/sim.${{matrix.test_num}}.edm4hep.root
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: simulation_${{matrix.test_num}}
  #         retention-days: 3
  #         path: out
